POST http://localhost:8080/signup
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGFzcyI6IkEiLCJlbXBsb3llZV9pZCI6MTUsImV4cGlyZWQiOjE3MjA0MDQ3MTV9.gtCnHEbjfjVlIwJRWj8U-FivY4sEpObWlOfrTTOXbbk

{
   "class": "C",
   "first_name": "Micah",
   "middle_name": "James",
   "last_name": "Edwards",
   "sex": "Male",
   "phone_number": 4048877913,
   "email": "medwards@vendex.com",
   "password": "Catbtin55!",
   "address": "33 Willow Street, Unit 45, Atlanta, GA 30344, USA"
}